name: Python CI

on:
  push:
    branches: [ "master"]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    name: Run Python Test Suite
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up MSYS2 with MinGW and LLVM
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: false
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-clang
            mingw-w64-x86_64-llvm
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            make

      - name: Build Apollo Compiler
        shell: msys2 {0}
        run: |
          cd "${{ github.workspace }}"
          cmake -B build -G "MinGW Makefiles" -S .
          cmake --build build

      - name: Run Test Runner
        shell: msys2 {0}
        run: |
          cd "${{ github.workspace }}"
          python tests/test.py

